### ISSUE TITLE
qemu savevm overwrites snapshots when tags used 0 and 1 consecutively

### ISSUE THREAD

**Issue by nasastry** [open-power-host-os/qemu#23] opened 2017-10-16 08:17 UTC
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=160120 </cde:info>

---Problem Description---
While creating snapshots when tag name '0' used in the very first and followed by tag name '1' then snapshot created with tag name '0' getting erased.

---Steps to Reproduce---
 1. Start the guest and connect to the qemu monitor

```
qemu-system-ppc64 --nographic -vga none -machine pseries,accel=kvm,kvm-type=HV -m 2G,slots=32,maxmem=16G -device virtio-blk-pci,drive=rootdisk -drive file=/home/nasastry/hostos-3.0-ppc64le.qcow2,if=none,cache=none,id=rootdisk,format=qcow2 -net nic,model=virtio -monitor telnet:127.0.0.1:1234,server,nowait
```

connect to monitor by 

`# telnet localhost 1234`

2. At the monitor issue the following commands
```
(qemu) info snapshots
There is no snapshot available.
(qemu) info status
VM status: running
(qemu) savevm 0
(qemu) info snapshots
List of snapshots present on all disks:
ID        TAG                 VM SIZE                DATE       VM CLOCK
--        0                      338M 2017-10-16 13:44:35   00:02:07.491
(qemu) info status
VM status: running
(qemu) savevm 1
(qemu) info snapshots
List of snapshots present on all disks:
ID        TAG                 VM SIZE                DATE       VM CLOCK
--        1                      340M 2017-10-16 13:45:12   00:02:18.835
(qemu) info status
VM status: running
```
snapshot created with tag '0' was replaced by tag '1'.
The same overwriting doesn't happen when used '0', '2' consecutively.

\# rpm -qf /usr/bin/qemu-system-ppc64
qemu-system-ppc-2.10.0-2.rel.gitc334a4e.el7.centos.ppc64le

**Comment by cdeadmin** [comment] 2017-10-16 16:55
------- Comment From KURZGREG@fr.ibm.com 2017-10-16 12:50:49 EDT-------
Even if I agree it is a bit misleading, I don't think this is a bug.

A snapshot is identified by a name computed either from an id, which is basically a
numerical counter starting at 1 for qcow2), or from a tag, which is a string (provided
by the user or automagically computed).

The savevm command is documented in 'info qemu':

?savevm [TAG|ID]?
     Create a snapshot of the whole virtual machine.  If TAG is
     provided, it is used as human readable identifier.  If there is
     already a snapshot with the same tag or ID, it is replaced.  More
     info at *note vm_snapshots::.

Back to your reproducer:

&gt; (qemu) savevm 0

This creates a snapshot with tag '0' and id '1'.

&gt; (qemu) savevm 1

This deletes snapshot with name '1' (ie, with id '1') and creates snapshot with tag '1' and id '1'

**Comment by cdeadmin** [comment] 2017-10-17 03:45
------- Comment From nasastry@in.ibm.com 2017-10-16 23:38:55 EDT-------
(In reply to comment #2)
&gt; Even if I agree it is a bit misleading, I don't think this is a bug.

I still feel this behavior has to be documented/fixed some where.

&gt; A snapshot is identified by a name computed either from an id, which is
&gt; basically a
&gt; numerical counter starting at 1 for qcow2)

Starting at '1' is in the code? or in some document? I guess code.

&gt; , or from a tag, which is a string
&gt; (provided
&gt; by the user or automagically computed).
&gt; 
&gt; The savevm command is documented in 'info qemu':
&gt; 
&gt; ?savevm [TAG|ID]?
&gt;      Create a snapshot of the whole virtual machine.  If TAG is
&gt;      provided, it is used as human readable identifier.  If there is
&gt;      already a snapshot with the same tag or ID, it is replaced.  More
&gt;      info at *note vm_snapshots::.
&gt; 
&gt; Back to your reproducer:
&gt; 
&gt; &gt; (qemu) savevm 0
&gt; 
&gt; This creates a snapshot with tag '0' and id '1'.

From the output of 'info snapshots' id '1' is not seen for tag '0' instead seeing an empty field.
Please refer to the below output.

ID        TAG                 VM SIZE                DATE       VM CLOCK
--        0                      338M 2017-10-16 13:44:35   00:02:07.491

If an ID shown as '1' in the above then user can understand the above documented stuff i.e &quot;If there is already a snapshot with the same tag or ID, it is replaced&quot;.

&gt; 
&gt; &gt; (qemu) savevm 1
&gt; 
&gt; This deletes snapshot with name '1' (ie, with id '1') and creates snapshot
&gt; with tag '1' and id '1'

When there is already a snapshot with id '1', why savevm created a new snapshot with the same id '1'? It has to create tag '1' and id '2'.

Opening this bugzilla to consider above points.
* If the user is not aware of this behavior, he might loose the data saved in the snapshot with tag '0'.

**Comment by cdeadmin** [comment] 2017-10-17 06:05
------- Comment From KURZGREG@fr.ibm.com 2017-10-17 01:55:48 EDT-------
(In reply to comment #3)
&gt; (In reply to comment #2)
&gt; &gt; Even if I agree it is a bit misleading, I don't think this is a bug.
&gt; 
&gt; I still feel this behavior has to be documented/fixed some where.
&gt; 
&gt; &gt; A snapshot is identified by a name computed either from an id, which is
&gt; &gt; basically a
&gt; &gt; numerical counter starting at 1 for qcow2)
&gt; 
&gt; Starting at '1' is in the code? or in some document? I guess code.
&gt; 
&gt; &gt; , or from a tag, which is a string
&gt; &gt; (provided
&gt; &gt; by the user or automagically computed).
&gt; &gt; 
&gt; &gt; The savevm command is documented in 'info qemu':
&gt; &gt; 
&gt; &gt; ?savevm [TAG|ID]?
&gt; &gt;      Create a snapshot of the whole virtual machine.  If TAG is
&gt; &gt;      provided, it is used as human readable identifier.  If there is
&gt; &gt;      already a snapshot with the same tag or ID, it is replaced.  More
&gt; &gt;      info at *note vm_snapshots::.
&gt; &gt; 
&gt; &gt; Back to your reproducer:
&gt; &gt; 
&gt; &gt; &gt; (qemu) savevm 0
&gt; &gt; 
&gt; &gt; This creates a snapshot with tag '0' and id '1'.
&gt; 
&gt; From the output of 'info snapshots' id '1' is not seen for tag '0' instead
&gt; seeing an empty field.
&gt; Please refer to the below output.
&gt; 
&gt; ID        TAG                 VM SIZE                DATE       VM CLOCK
&gt; --        0                      338M 2017-10-16 13:44:35   00:02:07.491
&gt; 
&gt; If an ID shown as '1' in the above then user can understand the above
&gt; documented stuff i.e &quot;If there is already a snapshot with the same tag or
&gt; ID, it is replaced&quot;.
&gt; 

You have a point. The '--' is annoying. I'll have a look.

&gt; &gt; 
&gt; &gt; &gt; (qemu) savevm 1
&gt; &gt; 
&gt; &gt; This deletes snapshot with name '1' (ie, with id '1') and creates snapshot
&gt; &gt; with tag '1' and id '1'
&gt; 
&gt; When there is already a snapshot with id '1', why savevm created a new
&gt; snapshot with the same id '1'? It has to create tag '1' and id '2'.
&gt; 

Because &quot;if there us already a snapshot with the same tag or ID, it is replaced&quot;... the only problem is that the id isn't shown.

&gt; Opening this bugzilla to consider above points.
&gt; * If the user is not aware of this behavior, he might loose the data saved
&gt; in the snapshot with tag '0'.

The behavior is documented. This all boils down to 'info snapshots' not showing the id. I'll investigate.

**Comment by cdeadmin** [comment] 2018-08-22 19:35
------- Comment From danielhb@br.ibm.com 2018-08-22 15:25:15 EDT-------
I've sent a patch set to the ML proposing a fix for this issue:

https://lists.gnu.org/archive/html/qemu-devel/2018-08/msg04658.html

In this series I've changed savevm/loadvm/delvm to not interpret the input arg
as an ID, just as a TAG. This change has little/zero impact on the existing
snapshot drivers which either didn't use the ID field at all or, as it is the
case with the QCOW2 driver, the ID is generated internally and never set by the
user anyway.  Libvirt isn't affected by this change since it has its own
snapshot mechanism.

**Comment by cdeadmin** [comment] 2018-09-14 16:56
------- Comment From seg@us.ibm.com 2018-09-14 12:48:21 EDT-------
No longer making plans for future hostos-specific bugs.

**Closed as completed by cdeadmin** 2018-09-14 16:56 UTC
